INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-100','Remazon Basics Blanket', 9.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-101','Remazon Basics BoomBox', 19.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-102','Remazon Basics Blaster', 29.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-103','Remazon Basics Interesting Programming Book', 10.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-104','Remazon Basics Comfy Pillow', 5.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-105','Remazon Basics Stylish Shoes 9000', 15.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-106','Remazon Basics Toothpaste', 7.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-107','Remazon Basics Yummy Dental Floss', 1.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-108','Remazon Basics Chocolate Fingers', 3.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-109','Remazon Basics Pint of Plain', 4.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-110','Remazon Basics JSON Object', 7.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-111','Remazon Basics Vaccine', 999.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-112','Remazon Basics Banana Phone', 45.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-113','Remazon Basics Avocado Toast PreMade', 12.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-114','Remazon Basics Extreme Princess Glitter', 20.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-115','Remazon Basics The Iconic Jersey', 63.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-116','Remazon Basics Fruit Tech Company Stocks', 1200.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-117','Remazon Basics Good Sense of  Humour', 122.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-118','Remazon Basics Best Ice Cream', 2.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-119','Remazon Basics Watch', 2000.99, TRUE)
INSERT INTO product (id, productname, price, isvisible ) VALUES ('BASICS-120','Remazon Basics Easter Egg Limited Edition', 13.99, TRUE)
